/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type Eventoner = ContractEventLog<{
  log: string;
  0: string;
}>;

export interface Contract1 extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): Contract1;
  clone(): Contract1;
  methods: {
    contribute(): PayableTransactionObject<void>;

    contributions(arg0: string): NonPayableTransactionObject<string>;

    getContribution(): NonPayableTransactionObject<string>;

    getName(returing: string): NonPayableTransactionObject<string>;

    owner(): NonPayableTransactionObject<string>;

    withdraw(): NonPayableTransactionObject<void>;
  };
  events: {
    Eventoner(cb?: Callback<Eventoner>): EventEmitter;
    Eventoner(options?: EventOptions, cb?: Callback<Eventoner>): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "Eventoner", cb: Callback<Eventoner>): void;
  once(
    event: "Eventoner",
    options: EventOptions,
    cb: Callback<Eventoner>
  ): void;
}
